"use client";

import { useEffect, useMemo, useState } from "react";
import type { KnowledgeBaseEntryType } from "@prisma/client";
import {
  formValuesToStructuredData,
  getDetailFieldsForType,
  structuredDataToFormValues,
  type DetailFieldDefinition,
} from "@/features/knowledge-base/knowledge-base-detail-fields";
import { autoGenerateDetailData } from "@/features/knowledge-base/knowledge-base-auto-generate";

type Props = {
  type: KnowledgeBaseEntryType;
  title: string;
  summary: string;
  content: string;
  value: Record<string, unknown> | null;
  onChange: (value: Record<string, unknown> | null) => void;
};

function FieldInput({
  field,
  value,
  onChange,
}: {
  field: DetailFieldDefinition;
  value: string;
  onChange: (value: string) => void;
}) {
  if (field.type === "textarea" || field.type === "list") {
    return (
      <textarea
        className="admin-textarea"
        rows={field.type === "list" ? 4 : 3}
        value={value}
        placeholder={field.placeholder}
        onChange={(e) => onChange(e.target.value)}
      />
    );
  }

  return (
    <input
      className="admin-input"
      value={value}
      placeholder={field.placeholder}
      onChange={(e) => onChange(e.target.value)}
    />
  );
}

export default function KnowledgeBaseDetailForm({
  type,
  title,
  summary,
  content,
  value,
  onChange,
}: Props) {
  const fields = useMemo(() => getDetailFieldsForType(type), [type]);
  const [formValues, setFormValues] = useState(() => structuredDataToFormValues(value, fields));
  const [autoResult, setAutoResult] = useState<{
    found: string[];
    missing: string[];
  } | null>(null);

  useEffect(() => {
    setFormValues(structuredDataToFormValues(value, fields));
  }, [value, fields]);

  function updateField(key: string, fieldValue: string) {
    const next = { ...formValues, [key]: fieldValue };
    setFormValues(next);
    const structured = formValuesToStructuredData(next, fields);
    onChange(Object.keys(structured).length > 0 ? structured : null);
  }

  function handleAutoGenerate() {
    const result = autoGenerateDetailData({
      title,
      summary,
      content,
      type,
      existing: value,
    });
    setFormValues(result.values);
    onChange(Object.keys(result.structuredData).length > 0 ? result.structuredData : null);
    setAutoResult({ found: result.found, missing: result.missing });
  }

  return (
    <div className="admin-kb-detail-form">
      <div className="admin-kb-detail-form-actions">
        <button type="button" className="admin-btn admin-btn--secondary admin-btn--small" onClick={handleAutoGenerate}>
          Tự tạo dữ liệu chi tiết
        </button>
      </div>

      {autoResult && (
        <div className="admin-kb-auto-result">
          {autoResult.found.length > 0 && (
            <p className="admin-field-hint">
              Dữ liệu tìm thấy: {autoResult.found.join(", ")}
            </p>
          )}
          {autoResult.missing.length > 0 && (
            <p className="admin-kb-warning">
              Dữ liệu còn thiếu: {autoResult.missing.join(", ")}
            </p>
          )}
        </div>
      )}

      <div className="admin-kb-detail-fields">
        {fields.map((field) => (
          <div key={field.key} className="admin-field">
            <label className="admin-label">{field.label}</label>
            {field.type === "list" && (
              <p className="admin-field-hint">Mỗi dòng một mục</p>
            )}
            <FieldInput
              field={field}
              value={formValues[field.key] ?? ""}
              onChange={(next) => updateField(field.key, next)}
            />
          </div>
        ))}
      </div>

      <details className="admin-ai-factory-advanced">
        <summary>Nâng cao — xem JSON</summary>
        <textarea
          className="admin-textarea admin-kb-context-text"
          readOnly
          rows={6}
          value={JSON.stringify(formValuesToStructuredData(formValues, fields), null, 2)}
        />
      </details>
    </div>
  );
}
