import type { KnowledgeBaseEntryType } from "@prisma/client";
import {
  formValuesToStructuredData,
  getDetailFieldsForType,
  structuredDataToFormValues,
} from "@/features/knowledge-base/knowledge-base-detail-fields";

export type AutoGenerateResult = {
  values: Record<string, string>;
  structuredData: Record<string, unknown>;
  found: string[];
  missing: string[];
};

function normalize(text: string): string {
  return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

function extractMoq(text: string): string | null {
  const match = text.match(/moq[^.\n]{0,40}/i);
  if (match) return match[0].trim();
  if (/tối thiểu|số lượng tối thiểu|minimum order/i.test(text)) {
    const line = text.split("\n").find((l) => /tối thiểu|moq/i.test(l));
    return line?.trim() ?? null;
  }
  return null;
}

function extractLeadTime(text: string): string | null {
  if (/lead time|leadtime|thời gian sản xuất|timeline/i.test(text)) {
    const line = text.split("\n").find((l) => /lead|timeline|thời gian/i.test(l));
    return line?.trim() ?? null;
  }
  if (/\d+\s*[-–]\s*\d+\s*ngày/.test(text)) {
    const match = text.match(/\d+\s*[-–]\s*\d+\s*ngày/);
    return match?.[0] ?? null;
  }
  return null;
}

function extractMaterials(text: string): string | null {
  const materials: string[] = [];
  if (/cotton/i.test(text)) materials.push("Cotton");
  if (/\bcvc\b/i.test(text)) materials.push("CVC");
  if (/poly|polyester/i.test(text)) materials.push("Poly");
  if (/chất liệu/i.test(text)) {
    const line = text.split("\n").find((l) => /chất liệu/i.test(l));
    if (line) return line.trim();
  }
  return materials.length > 0 ? materials.join(", ") : null;
}

function extractShipping(text: string): string | null {
  if (/giao hàng toàn quốc|giao hàng nationwide|ship toàn quốc/i.test(text)) {
    return "Giao hàng toàn quốc";
  }
  if (/giao hàng/i.test(text)) {
    const line = text.split("\n").find((l) => /giao hàng/i.test(l));
    return line?.trim() ?? null;
  }
  return null;
}

function extractServices(text: string): string[] {
  const services: string[] = [];
  if (/\boem\b/i.test(text)) services.push("OEM");
  if (/private label/i.test(text)) services.push("Private label");
  if (/\bin logo\b|in ấn/i.test(text)) services.push("In logo");
  if (/thêu/i.test(text)) services.push("Thêu");
  if (/may/i.test(text)) services.push("May");
  if (/đóng gói/i.test(text)) services.push("Đóng gói");
  return services;
}

function extractUseCases(text: string): string[] {
  const cases: string[] = [];
  if (/đồng phục|uniform/i.test(text)) cases.push("Đồng phục");
  if (/quà tặng|corporate gift/i.test(text)) cases.push("Quà tặng doanh nghiệp");
  if (/bán sỉ|wholesale/i.test(text)) cases.push("Bán sỉ");
  if (/xưởng in/i.test(text)) cases.push("Xưởng in");
  if (/đại lý|dealer/i.test(text)) cases.push("Đại lý");
  return cases;
}

export function autoGenerateDetailData(input: {
  title: string;
  summary: string;
  content: string;
  type: KnowledgeBaseEntryType;
  existing?: Record<string, unknown> | null;
}): AutoGenerateResult {
  const combined = normalize(`${input.title}\n${input.summary}\n${input.content}`);
  const fields = getDetailFieldsForType(input.type);
  const existingValues = structuredDataToFormValues(input.existing ?? null, fields);
  const values = { ...existingValues };
  const found: string[] = [];
  const missing: string[] = [];

  const moq = extractMoq(combined);
  if (moq && fields.some((f) => f.key === "moq")) {
    if (!values.moq) values.moq = moq;
    found.push("MOQ");
  } else if (fields.some((f) => f.key === "moq")) {
    missing.push("MOQ");
  }

  const leadTime = extractLeadTime(combined);
  if (leadTime && fields.some((f) => f.key === "leadTime")) {
    if (!values.leadTime) values.leadTime = leadTime;
    found.push("Lead time");
  } else if (fields.some((f) => f.key === "leadTime")) {
    missing.push("Lead time");
  }

  const material = extractMaterials(combined);
  if (material && fields.some((f) => f.key === "material")) {
    if (!values.material) values.material = material;
    found.push("Chất liệu");
  } else if (fields.some((f) => f.key === "material")) {
    missing.push("Chất liệu");
  }

  const shipping = extractShipping(combined);
  if (shipping && fields.some((f) => f.key === "shippingSupport")) {
    if (!values.shippingSupport) values.shippingSupport = shipping;
    found.push("Giao hàng");
  }

  const services = extractServices(combined);
  if (services.length > 0 && fields.some((f) => f.key === "services")) {
    if (!values.services) values.services = services.join("\n");
    found.push("Dịch vụ hỗ trợ");
  }

  const useCases = extractUseCases(combined);
  if (useCases.length > 0 && fields.some((f) => f.key === "useCases")) {
    if (!values.useCases) values.useCases = useCases.join("\n");
    found.push("Ứng dụng");
  }

  if (/đại lý|dealer/i.test(combined) && fields.some((f) => f.key === "targetAudience")) {
    if (!values.targetAudience) values.targetAudience = "Đại lý / xưởng in / shop online";
    found.push("Đối tượng đại lý");
  }

  if (/chính sách|policy/i.test(combined) && fields.some((f) => f.key === "policyName")) {
    if (!values.policyName) values.policyName = input.title.trim();
    found.push("Chính sách");
  }

  for (const field of fields) {
    const val = values[field.key]?.trim();
    if (!val && !missing.includes(field.label)) {
      if (!found.some((f) => f.toLowerCase().includes(field.label.toLowerCase()))) {
        missing.push(field.label);
      }
    }
  }

  const structuredData = formValuesToStructuredData(values, fields);
  return {
    values,
    structuredData,
    found: [...new Set(found)],
    missing: [...new Set(missing)].slice(0, 8),
  };
}
