import type { ImportTemplateDefinition } from "@/features/import/import-template-utils";

/**
 * Product bulk import templates.
 * Column names must match the ProductImportColumnMapping keys used by the import parser.
 */
export const PRODUCT_IMPORT_TEMPLATES: ImportTemplateDefinition[] = [
  // ── 1. Blank Apparel ──────────────────────────────────────────────────────
  {
    id: "blank-apparel",
    label: "Mẫu áo trơn",
    fileName: "attd-product-import-blank-apparel-template",
    requiredFields: ["category", "productName"],
    headers: [
      "category",
      "productName",
      "productCode",
      "shortDescription",
      "description",
      "material",
      "form",
      "fit",
      "colorName",
      "colorCode",
      "sizeName",
      "stockQty",
      "stockStatus",
      "defaultMoq",
      "wholesalePrice",
      "dealerPrice",
      "priceTiers",
      "supportsPrinting",
      "supportsEmbroidery",
      "supportsOem",
      "tags",
      "featuredImage",
      "gallery",
      "internalNote",
      "status",
    ],
    sampleRows: [
      {
        category: "Áo thun trơn",
        productName: "Áo thun CVC Basic unisex",
        productCode: "CVC-BASIC-U",
        shortDescription: "Áo thun CVC trơn unisex cho đại lý và xưởng in",
        description: "Áo thun CVC 65/35, form regular fit, khổ vải 30/1, phù hợp in lụa và in DTG. ATTD cung cấp sỉ từ 50 cái/màu.",
        material: "CVC 65/35",
        form: "Regular fit",
        fit: "Unisex",
        colorName: "Đen",
        colorCode: "BLK",
        sizeName: "M",
        stockQty: "500",
        stockStatus: "IN_STOCK",
        defaultMoq: "50",
        wholesalePrice: "45000",
        dealerPrice: "40000",
        priceTiers: "[{\"minQty\":50,\"price\":45000},{\"minQty\":200,\"price\":42000},{\"minQty\":500,\"price\":39000}]",
        supportsPrinting: "true",
        supportsEmbroidery: "false",
        supportsOem: "true",
        tags: "áo thun trơn, CVC, sỉ, unisex",
        featuredImage: "",
        gallery: "",
        internalNote: "Hàng chủ lực — nhập thường xuyên từ nhà máy TP.HCM",
        status: "ACTIVE",
      },
      {
        category: "Áo polo trơn",
        productName: "Áo polo cá sấu poly Basic",
        productCode: "PO-PIQUE-POLY",
        shortDescription: "Áo polo cá sấu polyester pique cho đại lý",
        description: "Áo polo pique poly, form regular fit, cổ bo 3 lá, phù hợp in/thêu logo đồng phục. Sỉ từ 50 cái.",
        material: "Cá sấu poly (Polyester pique)",
        form: "Regular fit",
        fit: "Regular",
        colorName: "Trắng",
        colorCode: "WHT",
        sizeName: "L",
        stockQty: "300",
        stockStatus: "IN_STOCK",
        defaultMoq: "50",
        wholesalePrice: "75000",
        dealerPrice: "68000",
        priceTiers: "",
        supportsPrinting: "true",
        supportsEmbroidery: "true",
        supportsOem: "true",
        tags: "áo polo, pique, đồng phục, sỉ",
        featuredImage: "",
        gallery: "",
        internalNote: "",
        status: "ACTIVE",
      },
      {
        category: "Áo thun trơn",
        productName: "Áo thun cotton 100% basic",
        productCode: "CT100-BASIC",
        shortDescription: "Áo thun cotton 100% trơn unisex",
        description: "Cotton 100%, 30/1, đơn giản, bền màu. Form unisex phổ thông, phù hợp in lụa và thêu vi tính.",
        material: "Cotton 100%",
        form: "Regular fit",
        fit: "Unisex",
        colorName: "Xanh navy",
        colorCode: "NVY",
        sizeName: "XL",
        stockQty: "200",
        stockStatus: "IN_STOCK",
        defaultMoq: "50",
        wholesalePrice: "55000",
        dealerPrice: "50000",
        priceTiers: "",
        supportsPrinting: "true",
        supportsEmbroidery: "true",
        supportsOem: "true",
        tags: "áo thun cotton, navy, sỉ",
        featuredImage: "",
        gallery: "",
        internalNote: "",
        status: "ACTIVE",
      },
    ],
  },

  // ── 2. Corporate Gift ─────────────────────────────────────────────────────
  {
    id: "corporate-gift",
    label: "Mẫu quà tặng doanh nghiệp",
    fileName: "attd-product-import-corporate-gift-template",
    requiredFields: ["category", "productName"],
    headers: [
      "category",
      "productName",
      "productCode",
      "shortDescription",
      "description",
      "material",
      "colorName",
      "dimensions",
      "capacity",
      "stockQty",
      "stockStatus",
      "defaultMoq",
      "wholesalePrice",
      "dealerPrice",
      "priceTiers",
      "supportsPrinting",
      "supportsEmbroidery",
      "supportsOem",
      "tags",
      "featuredImage",
      "gallery",
      "internalNote",
      "status",
    ],
    sampleRows: [
      {
        category: "Tote bag",
        productName: "Tote canvas basic 280gsm",
        productCode: "TOTE-CAN-BASIC",
        shortDescription: "Tote bag canvas 280gsm sỉ cho doanh nghiệp",
        description: "Tote canvas dày 280gsm, quai vải, kích thước 35x40cm, phù hợp in lụa và in nhiệt logo doanh nghiệp.",
        material: "Canvas 280gsm",
        colorName: "Be / Natural",
        dimensions: "35x40cm",
        capacity: "",
        stockQty: "1000",
        stockStatus: "IN_STOCK",
        defaultMoq: "100",
        wholesalePrice: "28000",
        dealerPrice: "24000",
        priceTiers: "[{\"minQty\":100,\"price\":28000},{\"minQty\":500,\"price\":25000}]",
        supportsPrinting: "true",
        supportsEmbroidery: "false",
        supportsOem: "true",
        tags: "tote bag, canvas, quà tặng, doanh nghiệp",
        featuredImage: "",
        gallery: "",
        internalNote: "Hàng best seller — giao hàng nhanh",
        status: "ACTIVE",
      },
      {
        category: "Bình giữ nhiệt",
        productName: "Bình giữ nhiệt inox 304 500ml",
        productCode: "BGN-INX500",
        shortDescription: "Bình giữ nhiệt inox 304 500ml có nắp vặn",
        description: "Bình inox 304 cao cấp, dung tích 500ml, giữ nhiệt 12h, giữ lạnh 24h. Phù hợp in laser khắc logo.",
        material: "Inox 304",
        colorName: "Bạc",
        dimensions: "",
        capacity: "500ml",
        stockQty: "500",
        stockStatus: "IN_STOCK",
        defaultMoq: "50",
        wholesalePrice: "95000",
        dealerPrice: "85000",
        priceTiers: "",
        supportsPrinting: "true",
        supportsEmbroidery: "false",
        supportsOem: "true",
        tags: "bình giữ nhiệt, inox, quà tặng, doanh nghiệp",
        featuredImage: "",
        gallery: "",
        internalNote: "",
        status: "ACTIVE",
      },
      {
        category: "Gift set doanh nghiệp",
        productName: "Combo quà tặng doanh nghiệp basic set 2",
        productCode: "GIFT-B2B-SET2",
        shortDescription: "Combo gồm tote canvas + bình giữ nhiệt + áo polo",
        description: "Gift set B2B: tote canvas 280gsm + bình inox 500ml + áo polo pique. Phù hợp tặng đối tác, khách VIP. MOQ 50 set.",
        material: "Canvas + Inox 304 + Pique Poly",
        colorName: "Xanh navy",
        dimensions: "",
        capacity: "",
        stockQty: "100",
        stockStatus: "IN_STOCK",
        defaultMoq: "50",
        wholesalePrice: "220000",
        dealerPrice: "195000",
        priceTiers: "",
        supportsPrinting: "true",
        supportsEmbroidery: "true",
        supportsOem: "true",
        tags: "gift set, quà tặng doanh nghiệp, combo, B2B",
        featuredImage: "",
        gallery: "",
        internalNote: "Đóng gói hộp riêng — tính thêm phí đóng gói",
        status: "ACTIVE",
      },
    ],
  },

  // ── 3. OEM Product ────────────────────────────────────────────────────────
  {
    id: "oem-product",
    label: "Mẫu OEM",
    fileName: "attd-product-import-oem-template",
    requiredFields: ["category", "productName"],
    headers: [
      "category",
      "productName",
      "productCode",
      "shortDescription",
      "description",
      "material",
      "form",
      "useCases",
      "targetCustomers",
      "defaultMoq",
      "supportsPrinting",
      "supportsEmbroidery",
      "supportsOem",
      "tags",
      "featuredImage",
      "gallery",
      "internalNote",
      "status",
    ],
    sampleRows: [
      {
        category: "OEM / Private label",
        productName: "Áo polo OEM theo yêu cầu doanh nghiệp",
        productCode: "OEM-POLO",
        shortDescription: "Sản xuất áo polo OEM từ chất liệu đến thiết kế theo yêu cầu",
        description: "ATTD nhận OEM áo polo full-service: chọn chất liệu, thiết kế cổ/tay, in hoặc thêu logo, đóng gói riêng theo thương hiệu khách hàng. MOQ linh hoạt từ 100 cái.",
        material: "Theo yêu cầu (CVC, Pique, Cotton)",
        form: "Theo yêu cầu",
        useCases: "Đồng phục công ty, quà tặng doanh nghiệp, private label",
        targetCustomers: "Doanh nghiệp, agency quảng cáo, reseller thương hiệu",
        defaultMoq: "100",
        supportsPrinting: "true",
        supportsEmbroidery: "true",
        supportsOem: "true",
        tags: "OEM, áo polo, private label, đồng phục",
        featuredImage: "",
        gallery: "",
        internalNote: "Lead time 10–14 ngày sau khi duyệt mẫu",
        status: "DRAFT",
      },
      {
        category: "OEM / Private label",
        productName: "Combo quà tặng doanh nghiệp OEM theo yêu cầu",
        productCode: "OEM-GIFT",
        shortDescription: "Gift set OEM custom: bình + áo + tote theo yêu cầu thương hiệu",
        description: "ATTD nhận OEM gift set trọn gói — chọn sản phẩm, thiết kế, in logo laser/lụa, đóng hộp riêng. Báo giá theo số lượng thực tế.",
        material: "Theo yêu cầu",
        form: "",
        useCases: "Quà tặng khách VIP, quà cuối năm, kỷ niệm thành lập",
        targetCustomers: "Doanh nghiệp lớn, agency tổ chức sự kiện",
        defaultMoq: "50",
        supportsPrinting: "true",
        supportsEmbroidery: "false",
        supportsOem: "true",
        tags: "OEM, gift set, private label, B2B",
        featuredImage: "",
        gallery: "",
        internalNote: "Cần confirm mẫu và thiết kế trước 5 ngày",
        status: "DRAFT",
      },
    ],
  },
];

export function getProductImportTemplate(id: string): ImportTemplateDefinition | undefined {
  return PRODUCT_IMPORT_TEMPLATES.find((t) => t.id === id);
}
