import type { QuotePriceVatType, QuoteSourceType, QuoteStatus } from "@prisma/client";

export type QuoteItemInput = {
  id?: string;
  pricingCalculationItemId?: string | null;
  productId?: string | null;
  variantId?: string | null;
  productNameSnapshot?: string | null;
  variantNameSnapshot?: string | null;
  description?: string | null;
  designMediaAssetId?: string | null;
  designImageUrl?: string | null;
  skuSnapshot?: string | null;
  colorSnapshot?: string | null;
  categorySnapshot?: string | null;
  genderSnapshot?: string | null;
  moqSnapshot?: number | null;
  itemNote?: string | null;
  productionLeadTime?: string | null;
  sampleFee?: number | null;
  sampleLeadTime?: string | null;
  quantity: number;
  unit?: string;
  baseUnitPrice?: number;
  serviceFee?: number;
  setupFee?: number;
  unitPrice?: number;
  discountAmount?: number;
  manualUnitPrice?: number | null;
  manualOverrideReason?: string | null;
  pricingSnapshot?: Record<string, unknown> | null;
  sortOrder?: number;
};

export type CreateQuoteInput = {
  sourceType?: QuoteSourceType;
  pricingCalculationId?: string | null;
  leadId?: string | null;
  customerId?: string | null;
  contactId?: string | null;
  priceGroupId?: string | null;
  status?: QuoteStatus;
  title?: string | null;
  validUntil?: string | null;
  quoteDate?: string | null;
  currency?: string;
  priceVatType?: QuotePriceVatType;
  customerCompanySnapshot?: string | null;
  customerTaxCodeSnapshot?: string | null;
  customerAddressSnapshot?: string | null;
  customerContactNameSnapshot?: string | null;
  customerContactTitleSnapshot?: string | null;
  customerPhoneSnapshot?: string | null;
  customerEmailSnapshot?: string | null;
  salesName?: string | null;
  salesPhone?: string | null;
  salesEmail?: string | null;
  salesAddress?: string | null;
  preparedBy?: string | null;
  discountAmount?: number;
  shippingFee?: number;
  vatRate?: number;
  manualTotalAmount?: number | null;
  manualOverrideReason?: string | null;
  customerNote?: string | null;
  internalNote?: string | null;
  terms?: string | null;
  items: QuoteItemInput[];
};

export type QuoteTotals = {
  subtotal: number;
  serviceTotal: number;
  setupTotal: number;
  discountAmount: number;
  shippingFee: number;
  vatRate: number;
  vatAmount: number;
  totalAmount: number;
  calculatedTotalAmount: number;
  manualOverride: boolean;
  manualTotalAmount: number | null;
};

export type ComputedQuoteItem = QuoteItemInput & {
  lineSubtotal: number;
  lineTotal: number;
  unitPrice: number;
  manualOverride: boolean;
};

export type QuoteListRecord = {
  id: string;
  quoteNo: string;
  status: QuoteStatus;
  title: string | null;
  totalAmount: number;
  manualOverride: boolean;
  manualTotalAmount: number | null;
  validUntil: string | null;
  createdAt: string;
  leadLabel: string | null;
  customerLabel: string | null;
};

export type PublicQuoteItem = {
  designImageUrl: string | null;
  colorSnapshot: string | null;
  categorySnapshot: string | null;
  genderSnapshot: string | null;
  productNameSnapshot: string | null;
  variantNameSnapshot: string | null;
  skuSnapshot: string | null;
  description: string | null;
  moqSnapshot: number | null;
  itemNote: string | null;
  quantity: number;
  unit: string;
  unitPrice: number;
  lineTotal: number;
  productionLeadTime: string | null;
  sampleFee: number | null;
  sampleLeadTime: string | null;
};

export type PublicQuoteDocument = {
  quoteNo: string;
  status: QuoteStatus;
  title: string | null;
  validUntil: string | null;
  quoteDate: string | null;
  currency: string;
  priceVatType: QuotePriceVatType;
  customerCompany: string | null;
  customerTaxCode: string | null;
  customerAddress: string | null;
  customerContactName: string | null;
  customerContactTitle: string | null;
  customerPhone: string | null;
  customerEmail: string | null;
  salesName: string | null;
  salesPhone: string | null;
  salesEmail: string | null;
  salesAddress: string | null;
  preparedBy: string | null;
  subtotal: number;
  discountAmount: number;
  shippingFee: number;
  vatRate: number;
  vatAmount: number;
  totalAmount: number;
  manualOverride: boolean;
  manualTotalAmount: number | null;
  customerNote: string | null;
  terms: string | null;
  items: PublicQuoteItem[];
  showProductionLeadTime: boolean;
  showSampleFee: boolean;
  showSampleLeadTime: boolean;
};
